### ISSUE TITLE
combine() does not include all group files

### ISSUE THREAD

**Issue by gnodeb** [canton7/fuelphp-casset#17]
If group contains file with defined minified version, that file will replace group content instead of appending it.

protected static function combine($type, $file_group, $minify, $inline)
{
...
if (static::$show_files_inline)
    $content .= PHP_EOL.'/\* '.$file['file'].' */'.PHP_EOL.PHP_EOL;
if ($file['minified'] || !$minify)
    $content = static::load_file($file['file'], $type, $file_group).PHP_EOL;
...
}

last line should be:
$content .= static::load_file($file['file'], $type, $file_group).PHP_EOL;

**Comment by canton7** [comment]
Brilliant, thank you!

**Comment by canton7** [comment]
I've pushed v1.14 with this fix
