### ISSUE TITLE
Setting paths in global config doesn't work

### ISSUE THREAD

**Issue by rob-mccann** [canton7/fuelphp-casset#2]
Hey,

I might be being a complete idiot but I've set the following in fuel/config/config.php

``` php
'casset' => array(
            'paths' => array(
                 'core' => 'assets/',
                 'admin' => 'assets/admin/'
            )
        )
```

but i get "Could not find namespace admin" when I try to use it. Any ideas what I'm doing wrong? Does it _have_ to be in fuel/packages/casset/config/casset.php ?

Kindest regards,
Rob

**Comment by canton7** [comment]
Casset uses Fuel's Config class, which handles all of the config file overwriting, etc.

By the looks of it, the easiest thing to do is to stick your config in `fuel/config/casset.php` -- it doesn't _appear_ there's a way to tell Fuel to look in a file of another name:

> All config files (db.php, routes.php, etc.) are loaded into groups of the same name, with the exception of the main config.php file.

Let me know if this solves your problem!
Antony

**Comment by rob-mccann** [comment]
Putting the config in a new file in fuel/config/casset.php worked

makes sense really :P
