### ISSUE TITLE
ErrorException [ Notice ]: Uninitialized string offset: 0

### ISSUE THREAD

**Issue by kusmierz** [canton7/fuelphp-casset#29]
I've ErrorException on

``` php
Casset::css('screen.css');
```

in PKGPATH/casset/classes/casset/cssurirewriter.php @ line 261

probably you have to change

``` php
        if ('/' !== $uri[0]               // root-relative
```

to

``` php
        if (!empty($uri[0]) && '/' !== $uri[0]                // root-relative
```

**Comment by canton7** [comment]
That file's actually third-party code (as seen by the notice at the top), which makes me think either the issue needs to be raised upstream, or I'm passing in an input incorrectly... Either way I'm loathe to change this code directly.

I'll be able to have a proper look at this when I'm back home on Monday or so.

**Comment by canton7** [comment]
Can you give me more details about your situation? What exactly did you do to prompt this error? Is it still an issue?

**Comment by kusmierz** [comment]
I don't know, I don't use Casset anymore :(
