### ISSUE TITLE
Change cache_path to public or static accessor function?

### ISSUE THREAD

**Issue by dmyers** [canton7/fuelphp-casset#34]
I currently override casset in my app to be able to get the path for things like I have a task that clears the cache folder and things, I realize there is the function, but it would be nice if you could just switch it's visiblity or add a static function to get it from the instance.

What do you think?

**Comment by canton7** [comment]
Sure. I'm tempted to go down the accessor route, as it leaves a bit more control. Do you just want a getter, or a setter as well?

**Comment by canton7** [comment]
I've left this undocumented, mainly because there wasn't a good place in the documentation to stick it.

`Casset::get_cache_path() anyway`
