### ISSUE TITLE
Add a "cache_retrieve" path

### ISSUE THREAD

**Issue by younes0** [canton7/fuelphp-casset#35]
Add a "cache_retrieve" path option to override cache_path when it comes to retrieve (and not store)  combined/minifed files.

This is a contribution enquiry and here's the usecase:
I'd like to store combined files in my "app\temp\combined" and not app\public\combined.
In apache, "www.mysite.com/combined" is a alias refering to "app\temp\combined"

**Comment by canton7** [comment]
You can currently do this with the filepath callback (I believe), although it is a bit of a hack.

I probably won't have time to implement this until the weekend. Unless, of course, you feel like submitting a patch :) Relevant lines are 803, 905, 928, plus the stuff in files_to_render. We also need to decide whether the get_filepath_\* functions return the original or 'rewritten' path.
