### ISSUE TITLE
Cache path is not fully configurable

### ISSUE THREAD

**Issue by assembledadam** [canton7/fuelphp-casset#37]
Cache files are written to a hardcoded base-dir (DOCROOT), and I need my cache files stored in a different directory.

I believe this should be fully configurable for people in my shoes that have separate static dirs/servers.

I'll put this together and submit a pull request.

**Comment by canton7** [comment]
Thanks! See also #32

**Comment by canton7** [comment]
Oops, this should have been closed along with #38
