### ISSUE TITLE
Even if necessary, white spaces were deleted.

### ISSUE THREAD

**Issue by microaijp** [canton7/fuelphp-casset#52]
casset.php
min => true

css
top: -webkit-calc(10% - 20px);
↓
top: -webkit-calc(10%-20px);　← css error.

**Comment by canton7** [comment]
I haven't used FuelPHP, or touched this, in 5 years, so I'm afraid development has stopped.

If you want to put together a PR that updates the CSS minification library (there's a link in the README), I'll accept it.

**Comment by microaijp** [comment]
Oh... Sorry and Thank you!
